pipeline:
  docker:
    image: plugins/docker
    repo: affixxx/drone-rb
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - 2.5.1

  telegram:
      image: appleboy/drone-telegram
      pull: true
      secrets: [ telegram_token, telegram_to ]
      when:
        status: [ success, failure ]
